---

- name: Correct xdg-user-dirs
  lineinfile: dest=/etc/xdg/user-dirs.defaults backrefs=yes
              regexp=^{{ item.key }}={{ item.old_value }}
              line={{ item.key }}={{ item.new_value }}
  with_items:
#    - { key: 'DESKTOP', old_value: 'Desktop', new_value: 'Desktop' }
    - { key: 'DOWNLOAD', old_value: 'Downloads', new_value: '' }
    - { key: 'TEMPLATES', old_value: 'Templates', new_value: '' }
    - { key: 'PUBLICSHARE', old_value: 'Public', new_value: '' }
    - { key: 'DOCUMENTS', old_value: 'Documents', new_value: '' }
    - { key: 'MUSIC', old_value: 'Music', new_value: '' }
    - { key: 'PICTURES', old_value: 'Pictures', new_value: '' }
    - { key: 'VIDEOS', old_value: 'Videos', new_value: '' }
